## Load the Data

In [0]:
import pandas as pd

In [0]:
bigmart= pd.read_csv('train_bm.csv')
bigmart.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [0]:
bigmart['Item_Type'].value_counts()

Fruits and Vegetables    1232
Snack Foods              1200
Household                 910
Frozen Foods              856
Dairy                     682
Canned                    649
Baking Goods              648
Health and Hygiene        520
Soft Drinks               445
Meat                      425
Breads                    251
Hard Drinks               214
Others                    169
Starchy Foods             148
Breakfast                 110
Seafood                    64
Name: Item_Type, dtype: int64

## Frrequency Encoding

In [0]:
temp = bigmart['Item_Type'].value_counts()
temp = pd.DataFrame(temp)
temp.head()

                       Item_Type
Fruits and Vegetables       1232
Snack Foods                 1200
Household                    910
Frozen Foods                 856
Dairy                        682

In [0]:
temp['Item_Type_count'] = temp['Item_Type']
temp['Item_Type'] = temp.index
temp.head()

                                   Item_Type  Item_Type_count
Fruits and Vegetables  Fruits and Vegetables             1232
Snack Foods                      Snack Foods             1200
Household                          Household              910
Frozen Foods                    Frozen Foods              856
Dairy                                  Dairy              682

In [0]:
bigmart = pd.merge(bigmart, temp, on='Item_Type', how='left')
bigmart[['Item_Identifier', 'Item_Type', 'Item_Type_count']].head()

  Item_Identifier              Item_Type  Item_Type_count
0           FDA15                  Dairy              682
1           DRC01            Soft Drinks              445
2           FDN15                   Meat              425
3           FDX07  Fruits and Vegetables             1232
4           NCD19              Household              910

In [0]:
bigmart[['Item_Identifier', 'Item_Type', 'Item_Type_count']].head(10)

  Item_Identifier              Item_Type  Item_Type_count
0           FDA15                  Dairy              682
1           DRC01            Soft Drinks              445
2           FDN15                   Meat              425
3           FDX07  Fruits and Vegetables             1232
4           NCD19              Household              910
5           FDP36           Baking Goods              648
6           FDO10            Snack Foods             1200
7           FDP10            Snack Foods             1200
8           FDH17           Frozen Foods              856
9           FDU28           Frozen Foods              856

## Mean Encoding (using Target Variable)

In [0]:
bigmart[['Item_Type', 'Item_Outlet_Sales']].head()

               Item_Type  Item_Outlet_Sales
0                  Dairy          3735.1380
1            Soft Drinks           443.4228
2                   Meat          2097.2700
3  Fruits and Vegetables           732.3800
4              Household           994.7052

In [0]:
bigmart.groupby('Item_Type')['Item_Outlet_Sales'].mean()

Item_Type
Baking Goods             1952.971207
Breads                   2204.132226
Breakfast                2111.808651
Canned                   2225.194904
Dairy                    2232.542597
Frozen Foods             2132.867744
Fruits and Vegetables    2289.009592
Hard Drinks              2139.221622
Health and Hygiene       2010.000265
Household                2258.784300
Meat                     2158.977911
Others                   1926.139702
Seafood                  2326.065928
Snack Foods              2277.321739
Soft Drinks              2006.511735
Starchy Foods            2374.332773
Name: Item_Outlet_Sales, dtype: float64